// <auto-generated />
namespace BIMStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tblproducts_warningqty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblproducts_warningqty));
        
        string IMigrationMetadata.Id
        {
            get { return "201810071820251_tblproducts_warningqty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
